### ISSUE TITLE
How do I use my own trained model file

### ISSUE THREAD

**Issue by Zumbalamambo** [qdraw/tensorflow-object-detection-tutorial#1]
I have trained model file using tensorflow for poets. It can basically identify if a fruit is an orange or apple. How do I use this model file with object detection?

**Comment by qdraw** [comment]
Dear Zumbalamambo,
You have a trained model with poets text. I asume that this plain text. The object detection api is usefull for images and video.

**Comment by Zumbalamambo** [comment]
can you please tell me how do I use opencv withobject detection so I can determine details about the region of interest?

**Comment by qdraw** [comment]
Hello Zumbalamambo,

Currently this tutorial is only available in Dutch. I have based it on: https://github.com/tensorflow/models/tree/master/object_detection https://github.com/tensorflow/models/blob/master/object_detection/g3doc/installation.md

I use https://github.com/qdraw/tensorflow-object-detection-tutorial/blob/master/cam_utils.py
for multi threading support for webcam

This is the script i use for object detection using my webcam. This is realtime
https://github.com/qdraw/tensorflow-object-detection-tutorial/blob/master/webcam_object_detection.py

This is a example where I use this for static jpeg images: https://github.com/qdraw/tensorflow-object-detection-tutorial/blob/master/image_object_detection.py

I hope i've answered your question

**Comment by Zumbalamambo** [comment]
is it possible to retrain the model to detect only humans and recognize their races?

**Comment by qdraw** [comment]
It is posible to retrain the model, if you have the training data. It is easier to make a filter for persons and look using the mtcnn algoritm for faces. https://github.com/davidsandberg/facenet/blob/master/src/align/align_dataset.py

**Comment by Zumbalamambo** [comment]
How the dataset has to be organized. As of now I have two folders called `Japanese` , `Americans`

Each folders contains people of the respective races. How can I use such a training data?

**Comment by qdraw** [comment]
Hello Zumbalamambo,

Yes it is possible.  But for this tutorial it is out of scope. For me race-detection is ethically dangerous. I'm sorry, but I can't help you with that.

Yours sincerely,
Dion

**Comment by Zumbalamambo** [comment]
@qdraw  Thank you. The one that Im building will be installed in a tourist spot where people from various countries appears. So they want statistics of each races and create analytics. Based on the analytics, they will do sales targeting the tourists. Thank you for the help by the way.
